import { index, route, type RouteConfig } from '@react-router/dev/routes'

export default [
  index('./routes/home.tsx'),
  route('explore', './routes/explore.tsx'),
  route('following', './routes/following.tsx'),
  route('upload', './routes/upload.tsx'),
  route('works/:id', './routes/works.$id.tsx'),
  route('creator/:handle', './routes/creator.$handle.tsx'),
  route('login', './routes/login.tsx'),
  route('register', './routes/register.tsx'),
  route('logout', './routes/logout.tsx'),
  route('forgot-password', './routes/forgot-password.tsx'),
  route('reset-password', './routes/reset-password.tsx'),
  route('verify-email', './routes/verify-email.tsx'),
  route('auth/github', './routes/auth.github.tsx'),
  route('auth/github/callback', './routes/auth.github.callback.tsx'),
  route('locale', './routes/locale.tsx'),
  route('account', './routes/account.tsx'),
  route('dashboard', './routes/dashboard.tsx'),
  route('dashboard/works/new', './routes/dashboard.works.new.tsx'),
  route('dashboard/works/:id/edit', './routes/dashboard.works.$id.edit.tsx'),
  route('admin', './routes/admin.tsx'),
  route('api/works', './routes/api.works.ts'),
  route('api/works/:id', './routes/api.works.$id.ts'),
  route('api/images', './routes/api.images.ts'),
  route('api/tags', './routes/api.tags.ts'),
  route('*', './routes/not-found.tsx'),
] satisfies RouteConfig
